// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require, exports) {
    var html, marked, readme;
    console.log('defined');
    readme = require('text!README.md');
    marked = require('marked');
    marked.setOptions({
      gfm: true,
      breaks: true
    });
    html = marked(readme);
    return document.querySelector('#readme').innerHTML = html;
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
